function createBar4PTTs(ymatrix1)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  bar matrix data

%  Auto-generated by MATLAB on 20-Apr-2015 15:31:33

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on',...
    'XTickLabel',{'PAT_{e,P}','PAT_{e,O}','PAT_{e,T}','PAT_{e,F}','PAT_{w,P}','PAT_{w,O}','PAT_{w,T}','PAT_{w,F}','PTT_{P}','PTT_{O}','PTT_{T}','PTT_{F}'},...
    'XTick',[1 2 3 4 5 6 7 8 9 10 11 12 ]);
%% Uncomment the following line to preserve the X-limits of the axes
% ylim(axes1,[-1 1]);
%% Uncomment the following line to preserve the Y-limits of the axes
xlim(axes1,[0 13]);
box(axes1,'on');
hold(axes1,'on');

% Create multiple lines using matrix input to bar
bar1 = bar(ymatrix1,'Parent',axes1);
set(bar1(3),'FaceColor',[0 0 1],'BarWidth',1);
set(bar1(2),'FaceColor',[0 1 0],'BarWidth',1);
set(bar1(1),'FaceColor',[0.600000023841858 0.200000002980232 0],...
    'BarWidth',1);

% Create xlabel
xlabel('Feature');

% Create ylabel
ylabel('Cerrelation');

