function plotBP_PTT_4_cali_ydh(X1, Y1, X2, Y2)
%CREATEFIGURE(X1, Y1, X2, Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 22-Apr-2015 16:53:17

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','运动前','Marker','*','LineStyle','none');

% Create plot
plot(X2,Y2,'DisplayName','运动后','Marker','*','LineStyle','none',...
    'Color',[1 0 0]);

% Create xlabel
xlabel('PTT (ms)','FontSize',11);

% Create ylabel
ylabel('BP (mmHg)','FontSize',11);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'FontSize',12);

